apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: github.com/redknee-lab/jhipstermongoms
      context: ../../jhipster-mongo-ms
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
